# # -*- coding: utf-8 -*-
# """cow-verification-model-triplet-v2.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1pRRjGMtHBBqppRW0KjO_BEbHlWbYLhnI
# """

# # -*- coding: utf-8 -*-
# """cow-verification-model-triplet-v2.ipynb"""

# !pip install timm scikit-learn pytorch-metric-learning -q

# import os
# from PIL import Image
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from torch.utils.data import Dataset, DataLoader
# from torchvision import transforms, models
# from pytorch_metric_learning import miners, losses
# from torch.optim.lr_scheduler import ReduceLROnPlateau
# from sklearn.metrics import roc_auc_score
# import torch.nn.functional as F
# import matplotlib.pyplot as plt


# print("Setup complete!")

# path = "/content/drive/MyDrive/Cow Verification System/BeefCattle_Muzzle_Individualized"
# train_path = os.path.join(path, "train")
# val_path = os.path.join(path, "val")

# # Quick check
# train_cows = [d for d in os.listdir(train_path) if os.path.isdir(os.path.join(train_path, d))]
# val_cows = [d for d in os.listdir(val_path) if os.path.isdir(os.path.join(val_path, d))]

# print(f"Total train cows: {len(train_cows)}")
# print(f"Total val cows: {len(val_cows)}")

# train_transform = transforms.Compose([
#     transforms.Resize((256, 256)),
#     transforms.RandomResizedCrop(224, scale=(0.75, 1.0)),
#     transforms.RandomHorizontalFlip(p=0.5),
#     transforms.RandomRotation(15),
#     transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3, hue=0.1),
#     transforms.RandomAffine(degrees=0, translate=(0.1, 0.1), scale=(0.9, 1.1)),
#     transforms.RandomGrayscale(p=0.1),
#     transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 2.0)),
#     transforms.ToTensor(),
#     transforms.RandomErasing(p=0.3, scale=(0.02, 0.2)),
#     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
# ])

# val_transform = transforms.Compose([
#     transforms.Resize((224, 224)),
#     transforms.ToTensor(),
#     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
# ])

# class TripletDataset(Dataset):
#     def __init__(self, root_dir, transform=None):
#         self.root_dir = root_dir
#         self.transform = transform

#         self.classes = [d for d in os.listdir(root_dir) if os.path.isdir(os.path.join(root_dir, d))]
#         self.class_to_images = {}

#         for cls in self.classes:
#             class_path = os.path.join(root_dir, cls)
#             images = [os.path.join(class_path, img) for img in os.listdir(class_path)]
#             if len(images) >= 2:
#                 self.class_to_images[cls] = images

#         self.classes = list(self.class_to_images.keys())
#         self.img_paths = []
#         self.labels = []

#         for i, cls in enumerate(self.classes):
#             for path in self.class_to_images[cls]:
#                 self.img_paths.append(path)
#                 self.labels.append(i)

#     def __len__(self):
#         return len(self.img_paths)

#     def __getitem__(self, idx):
#         img = Image.open(self.img_paths[idx]).convert("RGB")
#         if self.transform:
#             img = self.transform(img)
#         return img, self.labels[idx]

# train_dataset = TripletDataset(train_path, transform=train_transform)
# val_dataset = TripletDataset(val_path, transform=val_transform)

# train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=4, pin_memory=True)
# val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=4, pin_memory=True)

# print(f"Train samples: {len(train_dataset)}, Val samples: {len(val_dataset)}")

# images, labels = next(iter(train_loader))

# print(images.shape)

# class EmbeddingNet(nn.Module):
#     def __init__(self, embedding_dim=128):
#         super().__init__()
#         resnet = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
#         self.backbone = nn.Sequential(*list(resnet.children())[:-1])
#         self.fc = nn.Linear(2048, embedding_dim)

#     def forward(self, x):
#         x = self.backbone(x)
#         x = x.view(x.size(0), -1)
#         x = self.fc(x)
#         return nn.functional.normalize(x, p=2, dim=1)

# model = EmbeddingNet(embedding_dim=128)
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# model.to(device)
# print(f"Model moved to {device}")

# miner = miners.BatchHardMiner()
# criterion = losses.TripletMarginLoss(margin=1.0)

# optimizer = optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
# scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)

# def train_one_epoch(model, loader, optimizer, criterion, miner, device):
#     model.train()
#     total_loss = 0.0

#     for images, labels in loader:
#         images, labels = images.to(device), labels.to(device).long().view(-1)

#         optimizer.zero_grad()
#         embeddings = model(images)

#         a_idx, p_idx, n_idx = miner(embeddings, labels)
#         if len(a_idx) == 0:  # rare case
#             continue

#         loss = criterion(embeddings, labels, (a_idx, p_idx, n_idx))
#         loss.backward()
#         optimizer.step()

#         total_loss += loss.item()

#     return total_loss / len(loader) if len(loader) > 0 else 0.0


# def validate(model, loader, criterion, device):
#     model.eval()
#     total_loss = 0.0

#     with torch.no_grad():
#         for images, labels in loader:
#             images, labels = images.to(device), labels.to(device).long().view(-1)
#             embeddings = model(images)
#             a_idx, p_idx, n_idx = miner(embeddings, labels)

#             if len(a_idx) == 0:
#                 continue

#             loss = criterion(embeddings, labels, (a_idx, p_idx, n_idx))
#             total_loss += loss.item()

#     return total_loss / len(loader) if len(loader) > 0 else 0.0

# epochs = 5
# train_losses = []
# val_losses = []

# for epoch in range(epochs):
#     train_loss = train_one_epoch(model, train_loader, optimizer, criterion, miner, device)
#     val_loss = validate(model, val_loader, criterion, device)

#     train_losses.append(train_loss)
#     val_losses.append(val_loss)
#     scheduler.step(val_loss)

#     # Save model
#     # torch.save({
#     #     'epoch': epoch + 1,
#     #     'model_state_dict': model.state_dict(),
#     #     'optimizer_state_dict': optimizer.state_dict(),
#     #     'embedding_dim': 128,
#     # }, f"/content/drive/MyDrive/Cow Verification System/models/triplet-models/muzzle_model_epoch_{epoch+1}.pth")

#     print(f"Epoch {epoch+1}/{epochs} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")

# torch.save(model, "/content/drive/MyDrive/Cow Verification System/models/triplet-models/full_muzzle_model.pth")

# print("Training completed!")

# def compute_verification_metrics(model, loader, device):
#     model.eval()
#     all_embeddings = []
#     all_labels = []

#     with torch.no_grad():
#         for images, labels in loader:
#             images = images.to(device)
#             emb = model(images)
#             all_embeddings.append(emb.cpu())
#             all_labels.append(labels.cpu())

#     embeddings = torch.cat(all_embeddings, dim=0)
#     labels = torch.cat(all_labels, dim=0)

#     sim_matrix = F.cosine_similarity(embeddings.unsqueeze(1), embeddings.unsqueeze(0), dim=2)
#     label_matrix = (labels.unsqueeze(1) == labels.unsqueeze(0)).float()
#     mask = (torch.eye(len(labels)) == 0)

#     pos_sim = sim_matrix[mask & (label_matrix == 1)]
#     neg_sim = sim_matrix[mask & (label_matrix == 0)]

#     y_true = torch.cat([torch.ones_like(pos_sim), torch.zeros_like(neg_sim)]).numpy()
#     y_score = torch.cat([pos_sim, neg_sim]).numpy()

#     auc = roc_auc_score(y_true, y_score)
#     return auc

# val_auc = compute_verification_metrics(model, val_loader, device)
# print(f"Validation ROC-AUC: {val_auc:.4f}")

# plt.figure(figsize=(10, 5))
# plt.plot(train_losses, label='Train Loss')
# plt.plot(val_losses, label='Validation Loss')
# plt.xlabel('Epoch')
# plt.ylabel('Loss')
# plt.title('Training Progress')
# plt.legend()
# plt.grid(True)
# plt.show()

# # Clean load function
# def load_model(model_path, embedding_dim=128, device=None):
#     if device is None:
#         device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#     model = EmbeddingNet(embedding_dim=embedding_dim)
#     checkpoint = torch.load(model_path, map_location=device)
#     model.load_state_dict(checkpoint['model_state_dict'])
#     model.to(device)
#     model.eval()
#     return model


# model = torch.load("path/to/best_full_muzzle_model.pth", map_location=device)
# model.eval()

# # Correct get_embedding function
# def get_embedding(image_path, model, transform, device):
#     image = Image.open(image_path).convert("RGB")
#     image = transform(image).unsqueeze(0).to(device)

#     with torch.no_grad():
#         embedding = model(image)
#     return embedding

# # Test inference
# image1_path = "/content/drive/MyDrive/Cow Verification System/cow-cropped_muzzle_dataset/train/776_jpg.rf.2624f80f0999a3b3b2f74bc16b78a66c_0.jpg"
# image2_path = "/content/drive/MyDrive/Cow Verification System/cow-cropped_muzzle_dataset/train/778_jpg.rf.ef9acc284083d47318a83ec3956ba5d7_0.jpg"

# emb1 = get_embedding(image1_path, model, val_transform, device)
# emb2 = get_embedding(image2_path, model, val_transform, device)

# cos_sim = F.cosine_similarity(emb1, emb2).item()
# dist = torch.dist(emb1, emb2).item()

# print(f"Cosine Similarity: {cos_sim:.4f}")
# print(f"Euclidean Distance: {dist:.4f}")

# if cos_sim >= 0.75:
#     print("✅ Result: Same cow / Highly similar")
# else:
#     print("❌ Result: Different cows")

